### ISSUE TITLE
form functionality

### ISSUE THREAD

**Issue by stmcpeters** [stmcpeters/FlixFinder#8]
routes on the frontend to:
-create reviews
-edit reviews

**Comment by stmcpeters** [comment]
-creating reviews
- editing reviews

**Comment by stmcpeters** [comment]
progress so far: 
- added error handling and labels for each input field
- combines onSubmit() and handleSubmit() to validate and post new review 
- attempts to display reviews for the specific movie the user is currently viewing

areas of improvement:
- attempts to auto generate user ID and movie ID when creating new review, so user only has to write review body and submit. 
- attempts to use 'useParams' to fetch existing reviews for movie the user is currently viewing
- add frontend routes for editing/deleting reviews

**Comment by stmcpeters** [comment]
progress:
- still receiving this error when attempting to post new review. this issue is related to not being able to auto-generate user ID and movie ID (values the user would not know) when creating a new review. 

possible solutions:
- restructure the review form to populate user_id (using info of user currently logged in) and movie_id (using info from movie currently being displayed) automatically 
- restructure the reviews table in database to account for missing values (not ideal) - review_id (PKey), user_id (NOT NULL), movie_id (NOT NULL), review_body (NOT NULL), created_at (current_timestamp)

````
Error creating new review:  error: null value in column "user_id" of relation "reviews" violates not-null constraint

[0]     at /Users/steph/Desktop/Techtonica/Techtonica-assignments/flix-finder/server/node_modules/pg-pool/index.js:45:11
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0]     at async file:///Users/steph/Desktop/Techtonica/Techtonica-assignments/flix-finder/server/server.js:118:20 {
[0]   length: 244, 
[0]   severity: 'ERROR',
[0]   code: '23502',
[0]   detail: 'Failing row contains (17, null, null, test, 2024-11-07 16:28:31.843991).',
[0]   hint: undefined,
[0]   position: undefined,
[0]   internalPosition: undefined,
[0]   internalQuery: undefined,
[0]   where: undefined,
[0]   schema: 'public',
[0]   table: 'reviews',
[0]   column: 'user_id',
[0]   dataType: undefined,
[0]   constraint: undefined,
[0]   file: 'execMain.c',
[0]   line: '1889',
[0]   routine: 'ExecConstraints'
[0] }
````

**Comment by stmcpeters** [comment]
hey @derekhouck i've included a few notes of the issue i was having with the review form and the full error message. please let me know if you need anything further

**Comment by derekhouck** [comment]
> restructure the review form to populate user_id (using info of user currently logged in) and movie_id (using info from movie currently being displayed) automatically

This is the solution I would advise you to pursue. The less users have to worry about entering fields into a form, the easier of a user experience it will be for them.
